### ISSUE TITLE
TimeOut awaiting

### ISSUE THREAD

**Issue by Xiefengshang** [imtsuki/bupt-ncov-report-action#14]
rerun了几次都是这样，网页上已经登陆过了。
![image](https://user-images.githubusercontent.com/30817148/101273683-948f2100-37d2-11eb-9c14-965492014adc.png)

**Comment by zhangdabao96** [comment]
浏览器登录一下这个
https://app.bupt.edu.cn/uc/wap/login?redirect=https%3A%2F%2Fapp.bupt.edu.cn%2Fncov%2Fwap%2Fdefault%2Findex

**Comment by imtsuki** [comment]
这个和 GitHub 服务器当日网络条件的波动有关系。可以修改 `.github/workflows/main.yml` 增大运行次数试试？

**Comment by drcege** [comment]
今天开始频繁超时了，一直都不能成功。。。可能还是有些问题
