### ISSUE TITLE
Action error

### ISSUE THREAD

**Issue by littlepure2333** [imtsuki/bupt-ncov-report-action#3]
我fork之后填了 `BUPT_USERNAME`，`BUPT_PASSWORD`，`TG_BOT_TOKEN`，`TG_CHAT_ID`这四项
然后re-run 这个Action 出现了这个error

![Snipaste_2020-02-28_15-20-20](https://user-images.githubusercontent.com/36270711/75519451-3f9dcd80-5a3e-11ea-8615-e6b60dd8b41f.png)

**Comment by imtsuki** [comment]
看起来好像是 Telegram 通知部分的问题。

请尝试以下步骤：

- 去掉 `TG_BOT_TOKEN` 和 `TG_CHAT_ID` 后，能否正常运行？
- 如果问题在 Telegram 部分，尝试在地址栏直接访问 Telegram API 地址（`https://api.telegram.org/bot${替换为你的 TG_BOT_TOKEN}/sendMessage`），确认 TOKEN 是否正确？

**Comment by littlepure2333** [comment]
* 去掉`TG_BOT_TOKEN` 和 `TG_CHAT_ID` 后正常运行了👍
* `TG_BOT_TOKEN` 是正确的，难道是我 `TG_CHAT_ID` 填错了吗🤔 
> 我第一次搞这个telegram bot，是图中画横线的ID吗，我是用getMe方法返回的
> 
> ![Snipaste_2020-02-28_15-53-11](https://user-images.githubusercontent.com/36270711/75521336-7a096980-5a42-11ea-8e84-c6f624b5cd23.png)

**Comment by imtsuki** [comment]
`getMe` 返回的是 bot 自己的 id，不是 chat id。

你和 bot 的 chat id 可以这样获得：

1. 先向你的 bot 随便发一条消息（不是指令）；
2. 然后调用 [getUpdates API](https://core.telegram.org/bots/api#getupdates)；
3. 之后在返回值里就能看到 chat id 了。

这样做的原因是因为 Telegram Bot 没有权限直接发起私聊。

当然，你也可以创建一个 group 或者 channel，把 bot 加入进去；这样就可以直接填入 `@channelname` 作为 chat id。

**Comment by littlepure2333** [comment]
感谢宁详细的解释，果然成功了🎉
