### ISSUE TITLE
最近失败频率也太高了

### ISSUE THREAD

**Issue by banned2054** [imtsuki/bupt-ncov-report-action#39]
![image](https://user-images.githubusercontent.com/34962009/160534541-b43a87b7-7501-4ce8-af00-6e4ce96bd382.png)

**Comment by liuyichen12** [comment]
学校今天是不是改密码了？用户中心登录不了了

**Comment by banned2054** [comment]
![image](https://user-images.githubusercontent.com/34962009/161470809-67b76715-e820-4203-b838-33e7021c883d.png)
