### ISSUE TITLE
关于修改corn的时间的问题

### ISSUE THREAD

**Issue by dong-design** [imtsuki/bupt-ncov-report-action#46]
![Screenshot_20220402_095429](https://user-images.githubusercontent.com/67950595/161361143-4d4cfc9f-20d6-4f61-b6ef-8ffc26f05650.jpg)
请问我这样改是在0点20分自动运行么，很抱歉，我很小白

**Comment by imtsuki** [comment]
可以参考一下这个网站：https://crontab.guru
