### ISSUE TITLE
最近两天一直失败啊。。

### ISSUE THREAD

**Issue by shrimp2333** [imtsuki/bupt-ncov-report-action#55]
![image](https://user-images.githubusercontent.com/90206900/168440955-0e581b83-aa94-4d7f-ac3d-be04d55ccae5.png)

**Comment by dong-design** [comment]
你再更新一下fork  作者更新了

**Comment by shrimp2333** [comment]
> 你再更新一下fork 作者更新了

多谢，刚没注意到作者更新了
