### ISSUE TITLE
好像又挂了

### ISSUE THREAD

**Issue by AshiakerWang** [imtsuki/bupt-ncov-report-action#58]
![image](https://user-images.githubusercontent.com/14258909/179655924-85f06896-545a-465e-b79f-b4db6d68e447.png)

**Comment by RinChanNOWWW** [comment]
今天手动打卡一次，明天再看看？这个脚本需要头一天的信息的。

**Comment by Amorhlt** [comment]
可是我今天打了，然后手动再次运行还是不行

**Comment by imtsuki** [comment]
> 可是我今天打了，然后手动再次运行还是不行

明天再试试看？今天填报的信息，要到第二天才能获取到。

**Comment by Amorhlt** [comment]
> > 可是我今天打了，然后手动再次运行还是不行
> 
> 明天再试试看？今天填报的信息，要到第二天才能获取到。

好的好的，感谢！
