### ISSUE TITLE
寿终正寝

### ISSUE THREAD

**Issue by calcxx** [imtsuki/bupt-ncov-report-action#70]
> 10.取消“疫情防控通”打卡。师生如有发热、乏力、干咳等症状，应及时就医，如有异常情况及时报告，核酸检测阳性人员入驻健康驿站康复。 
> 北京邮电大学疫情防控工作领导小组 2022年12月8日

**Comment by IgarashiAkatuki** [comment]
这个东西终于失业了

**Comment by RinChanNOWWW** [comment]
![image](https://user-images.githubusercontent.com/33975039/206476081-cd47b98d-454b-4f17-90e8-f85ee3ef1161.png)

**Comment by Cyan-cake** [comment]
结束了，感谢它帮了我许多忙

**Comment by IgarashiAkatuki** [comment]
![`MDXY@I ZFK1LI ZD711`UX](https://user-images.githubusercontent.com/109781981/206477237-611f13ab-9ede-4a28-b037-b13ff41bbe95.png)
